{% import 'main.sv' as main with context -%}
//---------------------------------------------------------------------------------
// This file was autogenerated by PeakRDL-uvm
// Date (mm-dd-yyyy) : {{get_today_date}}  
// Time (hh:mm:ss)   : {{get_current_time}}
//---------------------------------------------------------------------------------

package {{package_name}};
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    {{ main.top()|indent}}
endpackage: {{package_name}}

