
// This file was autogenerated by PeakRDL-uvm
`ifndef TRU_REGISTERS_UVM_SV
`define TRU_REGISTERS_UVM_SV
    
    // Reg - trigger_routing_unit.tru_ssrn
    class trigger_routing_unit__tru_ssrn extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_ssrn)
        rand uvm_reg_field ssr;
        rand uvm_reg_field reserved1;
        rand uvm_reg_field lock;

        function new(string name = "trigger_routing_unit__tru_ssrn");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ssr = uvm_reg_field::type_id::create("ssr");
            this.ssr.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.reserved1 = uvm_reg_field::type_id::create("reserved1");
            this.reserved1.configure(this, 23, 8, "RW", 0, 'h0, 1, 1, 0);
            this.lock = uvm_reg_field::type_id::create("lock");
            this.lock.configure(this, 1, 31, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_ssrn

    // Reg - trigger_routing_unit.tru_mtr
    class trigger_routing_unit__tru_mtr extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_mtr)
        rand uvm_reg_field mtr0;
        rand uvm_reg_field mtr1;
        rand uvm_reg_field mtr2;
        rand uvm_reg_field mtr3;

        function new(string name = "trigger_routing_unit__tru_mtr");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.mtr0 = uvm_reg_field::type_id::create("mtr0");
            this.mtr0.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.mtr1 = uvm_reg_field::type_id::create("mtr1");
            this.mtr1.configure(this, 8, 8, "RW", 0, 'h0, 1, 1, 0);
            this.mtr2 = uvm_reg_field::type_id::create("mtr2");
            this.mtr2.configure(this, 8, 16, "RW", 0, 'h0, 1, 1, 0);
            this.mtr3 = uvm_reg_field::type_id::create("mtr3");
            this.mtr3.configure(this, 8, 24, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_mtr

    // Reg - trigger_routing_unit.tru_erraddr
    class trigger_routing_unit__tru_erraddr extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_erraddr)
        rand uvm_reg_field addr;
        rand uvm_reg_field reserved1;

        function new(string name = "trigger_routing_unit__tru_erraddr");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.addr = uvm_reg_field::type_id::create("addr");
            this.addr.configure(this, 12, 0, "RW", 0, 'h0, 1, 1, 0);
            this.reserved1 = uvm_reg_field::type_id::create("reserved1");
            this.reserved1.configure(this, 20, 12, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_erraddr

    // Reg - trigger_routing_unit.tru_stat
    class trigger_routing_unit__tru_stat extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_stat)
        rand uvm_reg_field lwerr;
        rand uvm_reg_field addrerr;
        rand uvm_reg_field reserved1;

        function new(string name = "trigger_routing_unit__tru_stat");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.lwerr = uvm_reg_field::type_id::create("lwerr");
            this.lwerr.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.addrerr = uvm_reg_field::type_id::create("addrerr");
            this.addrerr.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.reserved1 = uvm_reg_field::type_id::create("reserved1");
            this.reserved1.configure(this, 30, 2, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_stat

    // Reg - trigger_routing_unit.tru_gctl
    class trigger_routing_unit__tru_gctl extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_gctl)
        rand uvm_reg_field en;
        rand uvm_reg_field reset;
        rand uvm_reg_field mtrl;
        rand uvm_reg_field reserved1;
        rand uvm_reg_field lock;

        function new(string name = "trigger_routing_unit__tru_gctl");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = uvm_reg_field::type_id::create("en");
            this.en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.reset = uvm_reg_field::type_id::create("reset");
            this.reset.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.mtrl = uvm_reg_field::type_id::create("mtrl");
            this.mtrl.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.reserved1 = uvm_reg_field::type_id::create("reserved1");
            this.reserved1.configure(this, 28, 3, "RW", 0, 'h0, 1, 1, 0);
            this.lock = uvm_reg_field::type_id::create("lock");
            this.lock.configure(this, 1, 31, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_gctl

    // Reg - trigger_routing_unit.tru_rxdata
    class trigger_routing_unit__tru_rxdata extends uvm_reg;
        `uvm_object_utils(trigger_routing_unit__tru_rxdata)
        rand uvm_reg_field rxdata;

        function new(string name = "trigger_routing_unit__tru_rxdata");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rxdata = uvm_reg_field::type_id::create("rxdata");
            this.rxdata.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : trigger_routing_unit__tru_rxdata

    // Addrmap - trigger_routing_unit
    class trigger_routing_unit extends uvm_reg_block;
        `uvm_object_utils(trigger_routing_unit)
        rand trigger_routing_unit__tru_ssrn tru_ssrn;
        rand trigger_routing_unit__tru_mtr tru_mtr;
        rand trigger_routing_unit__tru_erraddr tru_erraddr;
        rand trigger_routing_unit__tru_stat tru_stat;
        rand trigger_routing_unit__tru_gctl tru_gctl;
        rand trigger_routing_unit__tru_rxdata tru_rxdata;

        function new(string name = "trigger_routing_unit");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_LITTLE_ENDIAN);
            this.tru_ssrn = trigger_routing_unit__tru_ssrn::type_id::create("tru_ssrn");
            this.tru_ssrn.configure(this);

            this.tru_ssrn.build();
            this.default_map.add_reg(this.tru_ssrn, 'h2000);
            this.tru_mtr = trigger_routing_unit__tru_mtr::type_id::create("tru_mtr");
            this.tru_mtr.configure(this);

            this.tru_mtr.build();
            this.default_map.add_reg(this.tru_mtr, 'h2004);
            this.tru_erraddr = trigger_routing_unit__tru_erraddr::type_id::create("tru_erraddr");
            this.tru_erraddr.configure(this);

            this.tru_erraddr.build();
            this.default_map.add_reg(this.tru_erraddr, 'h2010);
            this.tru_stat = trigger_routing_unit__tru_stat::type_id::create("tru_stat");
            this.tru_stat.configure(this);

            this.tru_stat.build();
            this.default_map.add_reg(this.tru_stat, 'h2014);
            this.tru_gctl = trigger_routing_unit__tru_gctl::type_id::create("tru_gctl");
            this.tru_gctl.configure(this);

            this.tru_gctl.build();
            this.default_map.add_reg(this.tru_gctl, 'h2018);
            this.tru_rxdata = trigger_routing_unit__tru_rxdata::type_id::create("tru_rxdata");
            this.tru_rxdata.configure(this);

            this.tru_rxdata.build();
            this.default_map.add_reg(this.tru_rxdata, 'h201c);
        endfunction : build
    endclass : trigger_routing_unit

`endif
